version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD?}
      POSTGRES_USER: postgres
    volumes:
      - .data/postgres:/var/lib/postgresql/data
  migration:
    depends_on:
      - db
    build:
      context: .
      dockerfile: prisma/Dockerfile.db
    restart: on-failure
    environment:
      DATABASE_URL: postgresql://postgres:${DATABASE_PASSWORD?}@db:5432/postgres?schema=public
  app:
    build: 
      context: .
      dockerfile: Dockerfile 
    restart: always
    depends_on:
     - db
     - migration
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:${DATABASE_PASSWORD?}@db:5432/postgres?schema=public
      EMAIL_FROM: noreply@example.com
      SECRET: helloworld
      NEXTAUTH_URL: http://localhost:3000
      # These are prefixed with `MAILGUN` because Heroku automatically provisions these ENV vars in prod
      # However you can use whatever mail server you like
      MAILGUN_SMTP_PASSWORD: password
      MAILGUN_PORT: 587
      MAILGUN_SMTP_LOGIN: test@ethereal.email
      MAILGUN_SMTP_SERVER: smtp.ethereal.email
      NEXT_TELEMETRY_DISABLED: 1
