services:
- type: web
  name: next-js
  env: node
  plan: starter plus
  buildCommand: npm i; npm run build
  startCommand: npm start
  envVars:
  - key: NODE_ENV
    value: production
  - key: NEXT_PUBLIC_INSPIRATION_USERNAME
    value: jreynoldsdev
  - key: NEXT_PUBLIC_INSPIRATION_USER_FULL
    value: Jake Reynolds
  - key: NEXT_PUBLIC_INSPIRATION_USER_TITLE
    value: Founder, README
  - key: EMAIL_FROM
    value: jake@readmefirst.co
  - key: DATABASE_URL
    fromDatabase:
      name: prod
      property: connectionString

databases:
  - name: prod
    plan: standard plus
    databaseName: readme
    user: readme