# Install dependencies only when needed
FROM node:lts AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apt-get install openssl
WORKDIR /app

# If using npm with a `package-lock.json` comment out above and use below instead
COPY package.json package-lock.json ./ 
COPY postinstall.js ./ 
COPY prisma/ .
RUN npm ci

COPY prisma/ .

CMD ["npm", "run", "migrate"]